1323 new new tooltips
univelop/yust_ui pull request #128
Opened 2024-04-12 16:16 UTC by plw307

Depends on univelop branch https://github.com/univelop/univelop/pull/2979

2024-04-14 15:06 UTC, plw307 commented on lib/src/widgets/yust_docs_builder.dart
> +    this.suffixChild,
Kann raus

2024-04-14 15:06 UTC, plw307 commented on lib/src/widgets/yust_docs_builder.dart
> +  final dynamic suffixChild;
Kann raus

2024-04-29 13:18 UTC, janneskoehler requested changes
S. Kommentare

2024-04-29 13:18 UTC, janneskoehler commented on lib/src/widgets/yust_docs_builder.dart
> +  final dynamic suffixChild;
Willst du das noch rausnehmen?

2024-04-29 15:32 UTC, maxsk-ger approved these changes
Approved as code reviewer

2024-05-31 06:27 UTC, merged