#1991 Create an edit button to file upload row
univelop/yust_ui pull request #94
Opened 2023-09-06 10:00 UTC by MoritzOtto

2023-09-07 10:00 UTC, philthefox requested changes
Nice feature :)

2023-09-11 05:40 UTC, MoritzOtto commented on lib/src/util/yust_file_helpers.dart
> +  String removeExtension(String file) {
Refactored: https://github.com/univelop/yust/pull/260
isValidFileName habe ich drin gelassen, da wir in diesem Status kein yustfile haben sondern nur ein Filename

2023-09-11 05:43 UTC, MoritzOtto commented on lib/src/widgets/yust_file_picker.dart
> +  Future<void> _doDeleteFile(YustFile yustFile) async {
Das wird die Methode viel Komplexer machen, da wir dann auch das setstate mit nem Flag versehen müssten. Ich habe die Methode deleteFile in deleteFileWithConfirmation umgenannt das es etwas klarer ist. https://dev.to/rweisleder/the-flag-parameter-anti-pattern-1j82

2024-05-29 21:17 UTC, janneskoehler approved these changes

2024-05-29 21:17 UTC, merged